//! Device wrapper for a tachometer. See docs for struct `Tachometer` for usage information.
//!

// A tachometer reports rotational speed (RPM).  In Zephyr, all tachometer drivers are regular
// `sensor` devices that expose their reading on the `SENSOR_CHAN_RPM` channel.  This wrapper is
// therefore agnostic to the specific tachometer hardware: it works with `zephyr,tach-gpio` as well
// as the various vendor peripherals (`nuvoton,npcx-tach`, `microchip,xec-tach`, etc.).
//
// Instances normally come from a phandle on another device (for example the `tach-device` property
// of a `pwm-fan`), so the constructor matches the signature generated by the devicetree tooling.

use super::{NoStatic, Unique};
use crate::raw;

/// A tachometer (RPM sensor).
///
/// (This is a wrapper around the `struct device` in Zephyr that represents any sensor reporting on
/// the `SENSOR_CHAN_RPM` channel).
/// 
/// # Using This Struct From The Devicetree:
/// 
/// In the devicetree, use compatible `"zephyr,tach-gpio"`, or any vendor-specific tachometer compatible.
/// Then, specify the following properties:
/// - `gpios`: A `gpios` Phandle specifying the desired GPIO controller, pin, and flags.
/// - `pulses-per-round`: How many electrical pulses correspond to a full 360 degree rotation.
/// 
/// Example:
/// 
/// 1. Configure a `zephyr,tach-gpio` (or vendor-specific tachometer) in the devicetree:
/// ```dts
/// my_tach: tachometer {
///     compatible = "zephyr,tach-gpio";
///     gpios = <&gpio0 15 GPIO_ACTIVE_HIGH>;
///     pulses-per-round = <2>;
/// };
///
/// ```
/// 2. Then, retrieve an instance of the object in your Rust code:
/// ```rust
/// zephyr::devicetree::my_tach::get_instance().unwrap()
/// ```
/// 
/// 3. You can also configure a tachometer and pass it into other devices, like a fan:
/// ```dts
/// my_tach: tachometer {
///     compatible = "zephyr,tach-gpio";
///     gpios = <&gpio0 15 GPIO_ACTIVE_HIGH>;
///     pulses-per-round = <2>;
/// };
///
/// fan0: my-fan {
///     compatible = "pwm-fan";
///     pwms = <&pwm0 0 25000 0>;
///     max-rpm = <5000>;
///     min-rpm = <1000>;
///     min-start-rpm = <1500>;
///     tachometer = <&my_tach>;  // pass the tachometer into the fan
/// };
/// ```
/// 
/// 4. Then, get an instance of the fan (which uses your tachometer internally):
/// ```rust
/// zephyr::devicetree::my_fan::get_instance().unwrap()
/// ```
/// 
pub struct Tachometer {
    device: *const raw::device,
}

impl Tachometer {
    /// Constructor, used by the devicetree generated code.
    pub(crate) unsafe fn new(
        unique: &Unique,
        _static: &NoStatic,
        device: *const raw::device,
    ) -> Option<Tachometer> {
        if !unique.once() {
            return None;
        }

        Some(Tachometer { device })
    }

    /// Read the current RPM from the tachometer.
    ///
    /// This fetches a fresh sample and returns the value of the `SENSOR_CHAN_RPM` channel.  Returns
    /// the Zephyr error code on failure.
    pub fn read_rpm(&self) -> Result<i32, ::core::ffi::c_int> {
        unsafe {
            let ret = raw::sensor_sample_fetch(self.device);
            if ret != 0 {
                return Err(ret);
            }

            let mut value: raw::sensor_value = Default::default();
            let ret = raw::sensor_channel_get(
                self.device,
                raw::sensor_channel_SENSOR_CHAN_RPM,
                &mut value,
            );
            if ret != 0 {
                return Err(ret);
            }

            // RPM is reported as a whole number in `val1`.
            Ok(value.val1)
        }
    }
}
