//! Device wrapper for a tachometer.
//!
//! A tachometer reports rotational speed (RPM).  In Zephyr, all tachometer drivers are regular
//! `sensor` devices that expose their reading on the `SENSOR_CHAN_RPM` channel.  This wrapper is
//! therefore agnostic to the specific tachometer hardware: it works with `zephyr,tach-gpio` as well
//! as the various vendor peripherals (`nuvoton,npcx-tach`, `microchip,xec-tach`, etc.).
//!
//! Instances normally come from a phandle on another device (for example the `tach-device` property
//! of a `pwm-fan`), so the constructor matches the signature generated by the devicetree tooling.

use super::{NoStatic, Unique};
use crate::raw;

/// A tachometer (RPM sensor).
///
/// This is a wrapper around the `struct device` in Zephyr that represents any sensor reporting on
/// the `SENSOR_CHAN_RPM` channel.
pub struct Tachometer {
    device: *const raw::device,
}

impl Tachometer {
    /// Constructor, used by the devicetree generated code.
    pub(crate) unsafe fn new(
        unique: &Unique,
        _static: &NoStatic,
        device: *const raw::device,
    ) -> Option<Tachometer> {
        if !unique.once() {
            return None;
        }

        Some(Tachometer { device })
    }

    /// Read the current RPM from the tachometer.
    ///
    /// This fetches a fresh sample and returns the value of the `SENSOR_CHAN_RPM` channel.  Returns
    /// the Zephyr error code on failure.
    pub fn read_rpm(&self) -> Result<i32, ::core::ffi::c_int> {
        unsafe {
            let ret = raw::sensor_sample_fetch(self.device);
            if ret != 0 {
                return Err(ret);
            }

            let mut value: raw::sensor_value = Default::default();
            let ret = raw::sensor_channel_get(
                self.device,
                raw::sensor_channel_SENSOR_CHAN_RPM,
                &mut value,
            );
            if ret != 0 {
                return Err(ret);
            }

            // RPM is reported as a whole number in `val1`.
            Ok(value.val1)
        }
    }
}
