# native_sim/native/64 configuration for the zephyr-odp sample.

CONFIG_LOG_BACKEND_RTT=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_RTT_CONSOLE=n
CONFIG_LOG_BACKEND_UART=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_DMA=n
CONFIG_DMA_MCUX_LPC=n

CONFIG_EMUL=y
CONFIG_I2C_EMUL=y
CONFIG_GPIO_EMUL=y
CONFIG_UART_EMUL=y
CONFIG_F75303=y
CONFIG_EMUL_F75303=y
